service: my-graphql-serverless

provider:
  name: aws
  runtime: nodejs20.x
  deploymentBucket:
    name: graphql-serverless-bucket # Specify your custom S3 bucket name
  stage: production
  region: us-east-1 # Specify your AWS region

functions:
  query:
    handler: handler.queryHandler
    events:
      - http:
          path: query
          method: post
          cors: true # Enable CORS if needed for public access

  mutation:
    handler: handler.mutationHandler
    events:
      - http:
          path: mutation
          method: post
          cors: true # Enable CORS if needed for public access

  subscription:
    handler: handler.subscriptionHandler
    events:
      - http:
          path: subscriptions
          method: post
          cors: true # Enable CORS if needed for public access

plugins:
  - serverless-offline
