name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest   // CICD PIPELINE

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Ensure this matches your project's Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Retrieve Secrets from AWS Secrets Manager
      run: |
        aws secretsmanager get-secret-value --secret-id mysql-secret --query SecretString --output json > secrets.json
        echo "::set-output name=SECRETS::$(cat secrets.json)"
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Run Deployment
      run: |
        npm run deploy --secrets="${{ steps.deploy.outputs.SECRETS }}"
      env:
        NODE_ENV: production
