name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install
      working-directory: my-graphql-lambda

    # Commented out or removed test step
    # - name: Run Tests
    #   run: npm test
    #   working-directory: my-graphql-lambda

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Deploy to AWS
      run: |
        npx serverless deploy --stage production
      working-directory: my-graphql-lambda
      env:
        AWS_ACCESS_KEY_ID: AKIA6ODU5VWACDYEJ2H2
        AWS_SECRET_ACCESS_KEY: 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
